included:
  - Sources

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message
disabled_rules:
  - identifier_name
  - type_name
type_body_length: 500
line_length: 300
file_length: 500
number_separator:
  minimum_length: 5

# Custom Rules
custom_rules:
  print_use:
    name: "Print use"
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    regex: "(print)|(debugPrint)"
    match_kinds:
      - identifier
    message: "Do not use print. Use `logger`  instead."
    severity: error
